### ISSUE TITLE
omero.scripts.Set always reports missing input

### ISSUE THREAD

**Issue by knabar** [openmicroscopy/openmicroscopy#5788]
When running the following script

```
from omero.rtypes import rstring, rlong
import omero.scripts as scripts
client = scripts.client('testscript.py', 'Test script',
    scripts.Set('Test set', optional=False).ofType(rlong(0)))
try:
    params = client.getInputs(unwrap=True)
    client.setOutput("Inputs", rstring(repr(params)))
finally:
    client.closeSession()
```

I always get the message `Invalid parameters: MISSING INPUT for "Test set":`, no matter what I enter as the argument.  Is this an issue with `Set` or am I using it incorrectly?

**Comment by joshmoore** [comment]
When testing from the CLI:

```
[hudson@ome-c6100-1 dist]$ bin/omero script launch /tests/knabar1.py
Enter value for "Test set": 1
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/cli.py", line 1620, in argv
    cli.invoke(args[1:])
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/cli.py", line 1095, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/cli.py", line 1172, in onecmd
    self.execute(line, previous_args)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/cli.py", line 1254, in execute
    args.func(args)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/plugins/script.py", line 412, in launch
    m = self._parse_inputs(args, params)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/plugins/script.py", line 757, in _parse_inputs
    rv.update(parse_input("%s=%s" % (key, value), params))
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/scripts.py", line 534, in parse_input
    % (key, param.prototype.__class__))
ValueError: No converter for: Test set (type=<class 'omero.rtypes.RSetI'>)
```

**Comment by joshmoore** [comment]
I haven't tracked down exactly where it happens, but this may be an issue with [IceMapper](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/src/omero/util/IceMapper.java#L461)

```
        } else if (o instanceof Collection) {
            List<RType> l = new ArrayList<RType>();
            for (Object i : (Collection) o) {
                l.add(toRType(i));
            }
            return rlist(l);
```

**Comment by joshmoore** [comment]
```
In [4]: rset([rstring("a")])
Out[4]:
object #0 (::omero::RSet)
{
    _val =
    {
        [0] = object #1 (::omero::RString)
        {
            _val = a
        }
    }
}

In [5]: s = rset([rstring("a")])

In [6]: client.setInput("s", s)

In [8]: client.getInput("s")
Out[8]:
object #0 (::omero::RList)
{
    _val =
    {
        [0] = object #1 (::omero::RString)
        {
            _val = a
        }
    }
}
```

Indeed.

**Comment by joshmoore** [comment]
Now seeing

```
Enter value for "Test set": 1,2
Job 106546 ready
Waiting....
Callback received: FINISHED

	*** out parameters ***
	* Inputs={'Test set': [1L, 2L]}
	***  done ***
```

**Comment by will-moore** [comment]
Testing #5790 with the script above, I get
```
Enter value for "Test set": 1,2
Bad parameters:
exception ::omero::ValidationException
{
    serverStackTrace = 
    serverExceptionClass = 
    message = Invalid parameters:
WRONG TYPE for "Test set": <class 'omero.rtypes.RListI'> != <class 'omero.rtypes.RSetI'>

}
```
I just copied the ```scripts.py``` over to dist, instead of rebuilding, so maybe I'm missing something?
Do I need to rebuild?

**Comment by will-moore** [comment]
OK, finally got it working:
```
Enter value for "Test set": 1,2
Job 105719 ready
Waiting....
Callback received: FINISHED

	*** out parameters ***
	* Inputs={'Test set': [1L, 2L]}
	***  done ***
```
