### ISSUE TITLE
OMERO.server cannot start if computer offline

### ISSUE THREAD

**Issue by mtbc** [openmicroscopy/openmicroscopy#6041]
Blitz-0.log complains,
```
Caused by: org.dom4j.DocumentException: hibernate.org Nested exception: hibernate.org
	at org.dom4j.io.SAXReader.read(SAXReader.java:484) ~[dom4j.jar:1.6.1]
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2238) ~[hibernate-core.jar:3.6.10.Final]
```
Perhaps it insists on first validating against an online XSD.

**Comment by mtbc** [comment]
Yesterday suffered some scary startup failures:
```
org.dom4j.DocumentException: Error on line 1 of document http://hibernate.org/dtd/hibernate-configuration-3.0.dtd : The markup declarations contained or pointed to by the document type declaration must be well-formed. Nested exception: The markup declarations contained or pointed to by the document type declaration must be well-formed.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482) ~[dom4j.jar:1.6.1]
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2238) ~[hibernate-core.jar:3.6.10.Final]
```
(There was a redirect to HTTPS.)
