### ISSUE TITLE
db.sql import fails

### ISSUE THREAD

**Issue by inDane** [openmicroscopy/openmicroscopy#6069]
From the installation-documentation:

`psql -h localhost -U "$OMERO_DB_USER" "$OMERO_DB_NAME" < OMERO.server/db.sql
`
This is the output:
```
...
CREATE TRIGGER
ALTER TABLE
ALTER TABLE
ERROR:  relation "i_logicalchannel_emissionwave" already exists
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
...
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

Trying to start omero.server anyways gives this:

```
omero@bi-ubu-srv-omero:~$ OMERO.server/bin/omero admin start
Traceback (most recent call last):
  File "OMERO.server/bin/omero", line 130, in <module>
    rv = omero.cli.argv()
  File "/opt/OMERO/OMERO.server/lib/python/omero/cli.py", line 1706, in argv
    cli.invoke(args[1:])
  File "/opt/OMERO/OMERO.server/lib/python/omero/cli.py", line 1159, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/OMERO/OMERO.server/lib/python/omero/cli.py", line 1236, in onecmd
    self.execute(line, previous_args)
  File "/opt/OMERO/OMERO.server/lib/python/omero/cli.py", line 1318, in execute
    args.func(args)
  File "/opt/OMERO/OMERO.server/lib/python/omero/plugins/prefs.py", line 74, in open_and_close_config
    return func(*args, **kwargs)
  File "/opt/OMERO/OMERO.server/lib/python/omero/plugins/admin.py", line 803, in start
    self.startasync(args, config)
  File "/opt/OMERO/OMERO.server/lib/python/omero/plugins/prefs.py", line 74, in open_and_close_config
    return func(*args, **kwargs)
  File "/opt/OMERO/OMERO.server/lib/python/omero/plugins/admin.py", line 754, in startasync
    self.checkice()
  File "/opt/OMERO/OMERO.server/lib/python/omero/plugins/admin.py", line 1651, in checkice
    popen = self.ctx.popen(["icegridnode", "--version"])
  File "/opt/OMERO/OMERO.server/lib/python/omero/cli.py", line 1409, in popen
    stdout=stdout, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

My versions:
```
omero@bi-ubu-srv-omero:~$ psql --version
psql (PostgreSQL) 10.9 (Ubuntu 10.9-1.pgdg18.04+1)
```

```
omero@bi-ubu-srv-omero:/opt/Ice-3.6.4/bin$ ./icegridadmin --version
3.6.4
```

```
omero@bi-ubu-srv-omero:$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
```

After i couldn't fix this manually, i figured i should try the docker container. It has the same issue.

Best regards
Ken

EDIT:
This is also weird, it says Using OMERO5.4 for version. (I downloaded 5.5)
```
omero@bi-ubu-srv-omero:~$ OMERO.server/bin/omero db script -f OMERO.server/db.sql --password "$OMERO_ROOT_PASS"
Using OMERO5.4 for version
Using 0 for patch
Using password from commandline
```

**Comment by jburel** [comment]
This is due to a problem with the latest version of PostgreSQL
See https://forum.image.sc/t/fyi-not-possible-to-create-new-omero-instance-with-latest-postgresql-versions/26929

Hopefully that problem will be fixed soon by the next release of PostgreSQL

**Comment by inDane** [comment]
thank you for your quick response. I will try to get another version.

**Comment by joshmoore** [comment]
This has now been fixed upstream. See https://github.com/ome/omero-install/issues/212 for more information.
